[Setting]
spotify_path           = /home/kuba/.local/share/spotify-launcher/install/usr/share/spotify
prefs_path             = /home/kuba/.config/spotify/prefs
spotify_launch_flags   = 
current_theme          = Bloom
color_scheme           = comfy
inject_theme_js        = 1
inject_css             = 1
replace_colors         = 1
overwrite_assets       = 1
check_spicetify_update = 1
always_enable_devtools = 0

[Preprocesses]
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 0
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.86.502.g8cd7fb22
with    = 2.43.2

[Patch]
